name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run pytest tests/test_server.py -v --tb=short

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Install dependencies
        run: uv sync

      - name: Start gRPC server in background
        run: |
          uv run python -m src.main &
          echo $! > server.pid
          # Wait for server to start
          sleep 5

      - name: Check if server is running
        run: |
          if ! ps -p $(cat server.pid) > /dev/null; then
            echo "Server failed to start"
            exit 1
          fi
          echo "Server is running with PID $(cat server.pid)"

      - name: Run integration tests
        run: uv run pytest tests/test_integration.py -v --tb=short

      - name: Stop server
        if: always()
        run: |
          if [ -f server.pid ]; then
            kill $(cat server.pid) || true
            rm server.pid
          fi

  lint:
    name: Lint Proto Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Buf
        uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint proto files
        run: buf lint

      - name: Check for breaking changes
        if: github.event_name == 'pull_request'
        run: buf breaking --against '.git#branch=${{ github.base_ref }}'
